# Generated by Django 6.0.8 on 2026-10-01 13:16

import competition.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('affected_scope', models.JSONField(default=dict)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_references', models.JSONField(default=list)),
                ('decision', models.TextField(blank=True)),
                ('material', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=80)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=24)),
                ('token', models.CharField(default=competition.models.mission_token, editable=False, max_length=64, unique=True)),
                ('fallback_code', models.CharField(default=competition.models.fallback_code, editable=False, max_length=12, unique=True)),
                ('hint', models.TextField()),
                ('symbol', models.CharField(blank=True, max_length=100)),
                ('qr_location', models.CharField(max_length=200)),
                ('clue_location', models.CharField(max_length=200)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('points', models.PositiveSmallIntegerField(default=1)),
                ('answer_verifiers', models.JSONField(default=list)),
                ('keyword', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('is_void', models.BooleanField(default=False)),
                ('is_practice', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('volunteer_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MissionResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('correction_type', models.CharField(max_length=32)),
                ('affected_scope', models.JSONField(default=dict)),
                ('evidence_references', models.JSONField(default=list)),
                ('source_decisions', models.JSONField(default=list)),
                ('reason', models.TextField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.incident')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('attempt_no', models.PositiveSmallIntegerField(default=1)),
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('delivery_mode', models.CharField(blank=True, choices=[('ONLINE_HUNT', 'Online treasure hunt'), ('EXTERNAL', 'Externally judged')], max_length=20)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('LOBBY', 'Lobby'), ('LIVE', 'Live'), ('FROZEN', 'Frozen'), ('ENDED', 'Ended'), ('PROVISIONAL', 'Provisional'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=16)),
                ('play_mode', models.CharField(choices=[('ONLINE', 'Online'), ('PAPER', 'Paper')], default='ONLINE', max_length=8)),
                ('rules_version', models.CharField(blank=True, max_length=40)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('rules_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('owners', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('advancement_count', models.PositiveIntegerField(blank=True, null=True)),
                ('active_budget_ms', models.PositiveBigIntegerField(default=5400000)),
                ('accumulated_active_ms', models.PositiveBigIntegerField(default=0)),
                ('live_started_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('control_version', models.PositiveIntegerField(default=0)),
                ('is_demo', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('prepare_content', 'Prepare competition content'), ('control_round', 'Control a live round'), ('adjudicate', 'Propose score corrections'), ('verify_evidence', 'Independently verify evidence'), ('publish_results', 'Publish verified results')],
            },
        ),
        migrations.CreateModel(
            name='ResultSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('revision', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('FINAL', 'Final')], max_length=12)),
                ('ranked_entries', models.JSONField(default=list)),
                ('qualifier_codes', models.JSONField(default=list)),
                ('cut_count', models.PositiveIntegerField(blank=True, null=True)),
                ('rules_digest', models.CharField(max_length=64)),
                ('evidence_digest', models.CharField(max_length=64)),
                ('appeal_deadline', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField()),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.resultsnapshot')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
        ),
        migrations.CreateModel(
            name='PaperWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('official_start', models.DateTimeField()),
                ('official_end', models.DateTimeField()),
                ('active_offset_ms', models.PositiveBigIntegerField()),
                ('remaining_budget_ms', models.PositiveBigIntegerField()),
                ('assigned_desks', models.JSONField()),
                ('clock_evidence', models.JSONField()),
                ('writer_isolation_evidence', models.JSONField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.incident')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round'),
        ),
        migrations.AddField(
            model_name='incident',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round'),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_digest', models.CharField(max_length=64)),
                ('schema_version', models.CharField(max_length=40)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dry_run_errors', models.JSONField(default=list)),
                ('preview', models.JSONField(default=list)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
        ),
        migrations.CreateModel(
            name='RoundPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('phase_type', models.CharField(choices=[('LIVE', 'Live'), ('FROZEN', 'Frozen')], max_length=8)),
                ('play_mode', models.CharField(choices=[('ONLINE', 'Online'), ('PAPER', 'Paper')], max_length=8)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('reason', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('leader_name', models.CharField(blank=True, max_length=100)),
                ('roster_reference', models.CharField(blank=True, max_length=200)),
                ('roster_digest', models.CharField(blank=True, max_length=64)),
                ('member_count', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('DISQUALIFIED', 'Disqualified')], default='ACTIVE', max_length=16)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('is_demo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionDecision',
            fields=[
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField()),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('answer_hmac', models.CharField(blank=True, max_length=64)),
                ('ingress_at', models.DateTimeField()),
                ('admitted_at', models.DateTimeField()),
                ('active_elapsed_ms', models.PositiveBigIntegerField()),
                ('rules_version', models.CharField(max_length=40)),
                ('answer_key_version', models.CharField(blank=True, max_length=40)),
                ('outcome', models.CharField(max_length=32)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('response_snapshot', models.JSONField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.mission')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=3, max_digits=10)),
                ('tie_metrics', models.JSONField(default=dict)),
                ('source_reference', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.importbatch')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.scorerevision')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_at', models.DateTimeField()),
                ('effective_active_ms', models.PositiveBigIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.mission')),
                ('source_resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.missionresolution')),
                ('source_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.submissiondecision')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated_wrong_count', models.PositiveIntegerField(default=0)),
                ('cooldown_until_active_ms', models.PositiveBigIntegerField(default=0)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.mission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('session_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_opened_at', models.DateTimeField()),
                ('last_opened_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('access_method', models.CharField(choices=[('QR', 'QR'), ('FALLBACK', 'Fallback')], max_length=12)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.mission')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='missionresolution',
            constraint=models.CheckConstraint(condition=models.Q(('maker', models.F('approver')), _negated=True), name='resolution_two_reviewers'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(fields=('number', 'attempt_no'), name='round_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 5)), name='round_number'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_no__gte', 1)), name='round_attempt_positive'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('active_budget_ms__gt', 0)), name='round_budget_positive'),
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.CheckConstraint(condition=models.Q(('advancement_count__isnull', True), ('advancement_count__gt', 0), _connector='OR'), name='round_cut_positive'),
        ),
        migrations.AddConstraint(
            model_name='resultsnapshot',
            constraint=models.UniqueConstraint(fields=('round', 'revision'), name='snapshot_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='resultsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('maker', models.F('approver')), _negated=True), name='snapshot_two_reviewers'),
        ),
        migrations.AddConstraint(
            model_name='paperwindow',
            constraint=models.CheckConstraint(condition=models.Q(('official_end__gte', models.F('official_start'))), name='paper_time_order'),
        ),
        migrations.AddConstraint(
            model_name='paperwindow',
            constraint=models.CheckConstraint(condition=models.Q(('recorder', models.F('verifier')), _negated=True), name='paper_two_reviewers'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.UniqueConstraint(fields=('round', 'public_id'), name='mission_public_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='mission',
            constraint=models.CheckConstraint(condition=models.Q(('points', 1)), name='mission_one_point'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('closed_at__gte', models.F('opened_at')), _connector='OR'), name='incident_time_order'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(fields=('round', 'file_digest'), name='import_file_unique'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('verifier__isnull', True), models.Q(('maker', models.F('verifier')), _negated=True), _connector='OR'), name='import_two_reviewers'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('committed_at__isnull', True), ('verifier__isnull', False), _connector='OR'), name='import_commit_verified'),
        ),
        migrations.AddConstraint(
            model_name='roundphase',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__gte', models.F('started_at'))), name='phase_time_order'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.CheckConstraint(condition=models.Q(('member_count__gte', 3), ('member_count__lte', 4)), name='team_member_count'),
        ),
        migrations.AddIndex(
            model_name='submissiondecision',
            index=models.Index(fields=['team', 'round', 'admitted_at'], name='competition_team_id_26e674_idx'),
        ),
        migrations.AddIndex(
            model_name='submissiondecision',
            index=models.Index(fields=['round', 'outcome', 'admitted_at'], name='competition_round_i_396f49_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissiondecision',
            constraint=models.UniqueConstraint(fields=('team', 'round', 'idempotency_key'), name='decision_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='scorerevision',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0), ('score__gte', 0), ('score__lte', models.F('max_score'))), name='score_range'),
        ),
        migrations.AddConstraint(
            model_name='scorerevision',
            constraint=models.CheckConstraint(condition=models.Q(('maker', models.F('verifier')), _negated=True), name='score_two_reviewers'),
        ),
        migrations.AddConstraint(
            model_name='completion',
            constraint=models.UniqueConstraint(fields=('team', 'mission'), name='completion_unique'),
        ),
        migrations.AddConstraint(
            model_name='completion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_decision__isnull', False), ('source_resolution__isnull', True)), models.Q(('source_decision__isnull', True), ('source_resolution__isnull', False)), _connector='OR'), name='completion_one_source'),
        ),
        migrations.AddConstraint(
            model_name='attemptstate',
            constraint=models.UniqueConstraint(fields=('team', 'mission'), name='attempt_team_mission_unique'),
        ),
        migrations.AddIndex(
            model_name='teamsession',
            index=models.Index(fields=['team', 'revoked_at', 'expires_at'], name='competition_team_id_35049a_idx'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('team', 'mission'), name='visit_team_mission_unique'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('count__gte', 1)), name='visit_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.CheckConstraint(condition=models.Q(('last_opened_at__gte', models.F('first_opened_at'))), name='visit_time_order'),
        ),
    ]
