# Generated by Django 6.0.8 on 2026-10-01 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_mission_prepared_by_round_approval_digest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLoginWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
    ]
