# Generated by Django 6.0.8 on 2026-10-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_teamloginwindow'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='phase_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
