# Generated by Django 6.0.8 on 2026-10-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_round_phase_started_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='submissiondecision',
            index=models.Index(fields=['team', 'round', 'active_elapsed_ms'], name='competition_team_id_ffffbf_idx'),
        ),
    ]
