# Generated by Django 6.0.8 on 2026-10-07 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_resultsnapshot_metadata_resultproposal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('correction_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('expected_version', models.PositiveIntegerField()),
                ('evidence_digest', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.incident')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.mission')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='missionresolution',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.resolutionproposal'),
        ),
    ]
