# Generated by Django 6.0.8 on 2026-10-07 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_resolutionproposal_missionresolution_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('expected_version', models.PositiveIntegerField()),
                ('evidence_digest', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaperSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('slip_number', models.CharField(max_length=64)),
                ('desk', models.CharField(max_length=100)),
                ('evaluated_at', models.DateTimeField()),
                ('active_elapsed_ms', models.PositiveBigIntegerField()),
                ('outcome', models.CharField(max_length=32)),
                ('answer_hmac', models.CharField(blank=True, max_length=64)),
                ('answer_key_version', models.CharField(blank=True, max_length=40)),
                ('evidence_references', models.JSONField(default=list)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.mission')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='competition.paperproposal')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'slip_number'), name='paper_slip_number_unique'), models.CheckConstraint(condition=models.Q(('maker', models.F('verifier')), _negated=True), name='paper_slip_two_reviewers')],
            },
        ),
    ]
