# Generated by Django 6.0.8 on 2026-10-07 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_paperproposal_paperslip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.TextField()),
                ('expected_version', models.PositiveIntegerField()),
                ('evidence_digest', models.CharField(max_length=64)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.incident')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
