# Generated by Django 6.0.8 on 2026-10-08 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0009_recoveryproposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_snapshot', models.JSONField(default=dict, editable=False)),
                ('visible', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=3000)),
                ('is_demo', models.BooleanField(default=False)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoundInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_snapshot', models.JSONField(default=dict, editable=False)),
                ('visible', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True, max_length=1000)),
                ('instructions', models.TextField(blank=True, help_text='General participant instructions. Keep clues, answers and interview questions private.', max_length=10000)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('contacts', models.JSONField(blank=True, default=list, help_text='Approved contacts: [{"name":"Name", "role":"Role", "location":"Desk", "channel":"Public contact"}]')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
