# Generated by Django 6.0.8 on 2026-10-08 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_eventannouncement_roundinformation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='delivery_mode',
            field=models.CharField(blank=True, choices=[('ONLINE_HUNT', 'Online treasure hunt'), ('CODING', 'Supervised Python/C competition'), ('EXTERNAL', 'Externally judged')], max_length=20),
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(max_length=16)),
                ('submitted_at', models.DateTimeField()),
                ('active_elapsed_ms', models.PositiveBigIntegerField()),
                ('manifest', models.JSONField(default=list)),
                ('manifest_digest', models.CharField(max_length=64)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.CreateModel(
            name='CodingJudgmentProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('reason', models.TextField()),
                ('evidence_digest', models.CharField(max_length=64)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.codingsubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodingJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(decimal_places=3, max_digits=7)),
                ('fully_correct_tasks', models.PositiveSmallIntegerField()),
                ('task_marks', models.JSONField(default=list)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='competition.codingjudgmentproposal')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.codingsubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=24)),
                ('category', models.CharField(choices=[('OUTPUT', 'Output'), ('DEBUG', 'Debug'), ('FILL', 'Fill'), ('SHORT', 'Short'), ('LOGIC', 'Logic')], max_length=16)),
                ('prompt', models.TextField(max_length=10000)),
                ('starter_code', models.TextField(blank=True, max_length=16000)),
                ('languages', models.JSONField(default=list)),
                ('points', models.DecimalField(decimal_places=3, max_digits=7)),
                ('version', models.CharField(max_length=40)),
                ('private_rubric', models.JSONField(default=dict, help_text='Private lab judging rubric. SHORT tasks need test_cases with unique id/input/expected fields.')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodingRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('action_id', models.UUIDField(unique=True)),
                ('revision', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=16)),
                ('body', models.TextField()),
                ('source_hash', models.CharField(max_length=64)),
                ('admitted_at', models.DateTimeField()),
                ('active_elapsed_ms', models.PositiveBigIntegerField()),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.codingtask')),
            ],
        ),
        migrations.CreateModel(
            name='CodingWorkstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('evidence_references', models.JSONField(default=list)),
                ('assigned_at', models.DateTimeField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.teamsession')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='codingsubmission',
            constraint=models.UniqueConstraint(fields=('round', 'team'), name='coding_final_once'),
        ),
        migrations.AddConstraint(
            model_name='codingtask',
            constraint=models.UniqueConstraint(fields=('round', 'public_id'), name='coding_task_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='codingtask',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0)), name='coding_task_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='codingrevision',
            constraint=models.UniqueConstraint(fields=('team', 'task', 'revision'), name='coding_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='codingworkstation',
            constraint=models.UniqueConstraint(fields=('round', 'team'), name='coding_one_station_per_team'),
        ),
        migrations.AddConstraint(
            model_name='codingworkstation',
            constraint=models.UniqueConstraint(fields=('round', 'label'), name='coding_station_unique'),
        ),
    ]
