# Generated by Django 6.0.8 on 2026-10-08 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_alter_round_delivery_mode_codingsubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingjudgment',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='workstation_evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddConstraint(
            model_name='codingjudgment',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='coding_score_bounds'),
        ),
    ]
