# Generated by Django 6.0.8 on 2026-10-09 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0013_importbatch_evidence_digest_importbatch_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="delivery_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONLINE_HUNT", "Online treasure hunt"),
                    ("CODING", "Supervised Python/C competition"),
                    ("EXTERNAL", "Externally judged"),
                    ("BUZZER", "Website buzzer with offline answers"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BuzzerQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("public_id", models.CharField(max_length=40)),
                ("stage", models.PositiveSmallIntegerField()),
                ("version", models.CharField(max_length=40)),
                ("source_reference", models.CharField(max_length=200)),
                ("private_content", models.JSONField(default=dict)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.round"
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuzzerWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                ("round_version", models.PositiveIntegerField()),
                ("opened_at", models.DateTimeField()),
                ("reason", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.buzzerquestion"
                    ),
                ),
                (
                    "round",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.round"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuzzerPress",
            fields=[
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("received_at", models.DateTimeField()),
                ("admitted_at", models.DateTimeField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.teamsession"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.team"
                    ),
                ),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.buzzerwindow"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuzzerClosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField()),
                ("reason", models.TextField()),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "window",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.buzzerwindow"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="buzzerquestion",
            constraint=models.UniqueConstraint(
                fields=("round", "public_id"), name="buzzer_question_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="buzzerquestion",
            constraint=models.CheckConstraint(
                condition=models.Q(("stage__gte", 1), ("stage__lte", 5)), name="buzzer_stage_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="buzzerwindow",
            constraint=models.UniqueConstraint(
                fields=("round", "version"), name="buzzer_window_version"
            ),
        ),
        migrations.AddIndex(
            model_name="buzzerpress",
            index=models.Index(fields=["window", "team", "received_at"], name="buzzer_team_time"),
        ),
    ]
