# Generated by Django 6.0.8 on 2026-10-09 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0014_alter_round_delivery_mode_buzzerquestion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuzzerAnswerEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("action_id", models.UUIDField(unique=True)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("CORRECT", "Correct"),
                            ("WRONG", "Wrong"),
                            ("NO_ANSWER", "No answer"),
                        ],
                        max_length=16,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("source_reference", models.CharField(max_length=200)),
                ("completed_at", models.DateTimeField()),
                ("active_elapsed_ms", models.PositiveBigIntegerField()),
                ("priority_evidence", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "press",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.buzzerpress"
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.team"
                    ),
                ),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.buzzerwindow"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("window", "team"), name="buzzer_answer_once")
                ],
            },
        ),
        migrations.CreateModel(
            name="BuzzerScoreRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("payload", models.JSONField()),
                ("evidence_digest", models.CharField(max_length=64)),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.importbatch"
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="competition.buzzerscorerevision",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "window",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="competition.buzzerwindow"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("maker", models.F("verifier")), _negated=True),
                        name="buzzer_score_two_reviewers",
                    )
                ],
            },
        ),
    ]
