# Generated by Django 6.0.8 on 2026-10-10 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0015_buzzeranswerevidence_buzzerscorerevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenCardRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField()),
                ('source_reference', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.importbatch')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.greencardrevision')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('maker', models.F('verifier')), _negated=True), name='green_card_two_reviewers')],
            },
        ),
    ]
