# Generated by Django 6.0.8 on 2026-10-10 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_green_card_qualification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaygroundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('content_base64', models.TextField()),
                ('metadata', models.JSONField()),
                ('participants', models.JSONField()),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.round')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('round', 'sha256'), name='wayground_report_unique')],
            },
        ),
    ]
